language: cpp
compiler:
  - gcc
#  - clang
# Change this to your needs
install:
  - sudo apt-add-repository ppa:ubuntu-sdk-team/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install liblog4cpp5-dev libqt5opengl5-dev
  - sudo apt-get install libglew-dev libglm-dev
script:
  - wget https://gist.github.com/sabus/787d56cfebd35f251bff/raw/f6e00c3c00a3f970e1652cf8cd1d0b1e03bc0b5e/FindGLEW.cmake -P cmake
  - mkdir build && cd build
  - cmake ../
  - make
